- hosts: all
  vars:
    - docker_version: '18.09.0-3.el7.x86_64'
  tasks:
  - name: Install docker
    yum:
      name:
        - "docker-ce-{{ docker_version }}"
        - "docker-ce-cli-{{ docker_version }}"
        - containerd.io
      state: present
    when: (docker_version != "")

